
eta_wm_lambda_1_scheme = {'program_name' : 'Half-width finder for WM/GWM pre-catched free paramenter',
                          'arguments_menu' : {'-f' : {'long_string' : '--file-config',
                             'action' : 'store',
                             'help' : 'Parse a config file for the program.',
                             'type' : str,
                             'nargs' : '?',
                             'default' : None},
                     '-i' : {'long_string' : '--input-file',
                             'action' : 'store',
                             'help' : 'Sets the auxiliary file to calculate ...',
                             'nargs' : '?',
                             'type' : str,
                             'default' : ''},
                     '-o' : {'long_string' : '--output-file',
                             'action' : 'store',
                             'help' : 'Sets the output file of the calculation.',
                             'nargs' : '?',
                             'type' : str,
                             'default' : ''},
                     '-r' : {'long_string' : '--raster-dimension',
                             'action' : 'store',
                             'help' : 'Sets the raster dimension size',
                             'type': int,
                             'nargs' : 2,
                             'default' : [4096,2048]}
                    }}
